### ISSUE TITLE
Psalm integration

### ISSUE THREAD

**Issue by boesing** [laminas-api-tools/api-tools-welcome#11]
### Feature Request

|    Q        |   A
|------------ | ------
| QA    | yes

#### Summary

As decided during the [Technical-Steering-Committee Meeting on August 3rd, 2020](https://github.com/laminas/technical-steering-committee/blob/main/meetings/minutes/2020-08-03-TSC-Minutes.md#vote-on-static-analysis-tooling), Laminas wants to implement [vimeo/psalm](https://github.com/vimeo/psalm) in all packages.

Implementing psalm is quite easy.

#### Required
- [ ] Create a `psalm.xml` in the project root
- [ ] Copy and paste the contents from this [psalm.xml.dist](https://github.com/mezzio/repo-template/blob/6124090610ef1c6d6b0c80a063cafacc3ec68f38/psalm.xml.dist)
- [ ] Run `$ composer require --dev vimeo/psalm`
- [ ] Run `$ vendor/bin/psalm --set-baseline=psalm-baseline.xml`
- [ ] Add a composer script `static-analysis` with the command `psalm --shepherd --stats`
- [ ] Add a new line to `script:` in `.travis.yml`: `- if [[ $TEST_COVERAGE == 'true' ]]; then composer static-analysis ; fi`
- [ ] Remove phpstan from the project (`phpstan.neon.dist`, `.travis.yml` entry, `composer.json` `require-dev` and `scripts`)

##### Optional
- [ ] Fix as many psalm errors as possible.

**Comment by superrosko** [comment]
@boesing, I added:

Run `$ composer require --dev psalm/plugin-phpunit
`
becouse [psalm.xml.dist](https://github.com/mezzio/repo-template/blob/6124090610ef1c6d6b0c80a063cafacc3ec68f38/psalm.xml.dist) need:
```
    <plugins>
        <pluginClass class="Psalm\PhpUnitPlugin\Plugin"/>
    </plugins>
```

remove psalm/plugin-phpunit and this rule from psalm.xml?

**Comment by boesing** [comment]
oh... didnt realize that there is a plugin required in that example file... 
its fine if you add the plugin aswell. that explains why all those PR does have the plugin required 😅

**Comment by superrosko** [comment]
@boesing, OK. And i fix  .travis.yml as it was said in https://github.com/laminas-api-tools/api-tools-http-cache/pull/6.
If the PRs is correct, then you can put a label `hacktoberfest-accepted` on it?
